site_name:        Expectations.jl
repo_url:         https://github.com/econtoolkit/Expectations.jl
site_description: A package to help with numerical expectations of random variables and their functions. 
site_author:      QuantEcon, jlperla, arnavs

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
